#!/bin/python

import sys

def candies(n, arr):
    candy = [1]*n
    for i in range(1,len(arr)):
        if arr[i] > arr[i-1]:
            candy[i] = candy[i-1] + 1
    #print candy            
    for j in range(len(arr)-1,0,-1):
        if arr[j] < arr[j-1]:
            if candy[j] >= candy[j-1]:
                candy[j-1] = candy[j] + 1  
    #print candy
    #print arr
    return sum(candy)            
    
    # Complete this function

if __name__ == "__main__":
    n = int(raw_input().strip())
    arr = []
    arr_i = 0
    for arr_i in xrange(n):
        arr_t = int(raw_input().strip())
        arr.append(arr_t)
    result = candies(n, arr)
    print result
