#!/bin/python

import sys


q = int(raw_input().strip())
for a0 in xrange(q):
    n = int(raw_input().strip())
    M = []
    for M_i in xrange(n):
        M_temp = map(int,raw_input().strip().split(' '))
        M.append(M_temp)
    row_sum = []
    col_sum = [0] * n
    for rows in M:
        row_sum.append(sum(rows))
        for c in range(n):
            col_sum[c] += rows[c]
    row_sum.sort()
    col_sum.sort()
    if row_sum == col_sum:
        print "Possible"
    else:
        print "Impossible"    
